export const OWNER_REVIEW_SUBMISSION_REQUEST = 'OWNER_REVIEW_SUBMISSION_REQUEST';
export const OWNER_REVIEW_SUBMISSION_SUCCESS = 'OWNER_REVIEW_SUBMISSION_SUCCESS';
export const OWNER_REVIEW_SUBMISSION_ERROR = 'OWNER_REVIEW_SUBMISSION_ERROR'; 

export const CONTRACT_REVIEW_SUBMISSION_REQUEST = 'CONTRACT_REVIEW_SUBMISSION_REQUEST';
export const CONTRACT_REVIEW_SUBMISSION_SUCCESS = 'CONTRACT_REVIEW_SUBMISSION_SUCCESS';
export const CONTRACT_REVIEW_SUBMISSION_ERROR = 'CONTRACT_REVIEW_SUBMISSION_ERROR'; 

export const DOCUMENT_REVIEW_SUBMISSION_REQUEST = 'DOCUMENT_REVIEW_SUBMISSION_REQUEST';
export const DOCUMENT_REVIEW_SUBMISSION_SUCCESS = 'DOCUMENT_REVIEW_SUBMISSION_SUCCESS';
export const DOCUMENT_REVIEW_SUBMISSION_ERROR = 'DOCUMENT_REVIEW_SUBMISSION_ERROR'; 

export const HOTEL_REVIEW_SUBMISSION_REQUEST = 'HOTEL_REVIEW_SUBMISSION_REQUEST';
export const HOTEL_REVIEW_SUBMISSION_SUCCESS = 'HOTEL_REVIEW_SUBMISSION_SUCCESS';
export const HOTEL_REVIEW_SUBMISSION_ERROR = 'HOTEL_REVIEW_SUBMISSION_ERROR'; 

export const CATEGORY_REVIEW_SUBMISSION_REQUEST = 'CATEGORY_REVIEW_SUBMISSION_REQUEST';
export const CATEGORY_REVIEW_SUBMISSION_SUCCESS = 'CATEGORY_REVIEW_SUBMISSION_SUCCESS';
export const CATEGORY_REVIEW_SUBMISSION_ERROR = 'CATEGORY_REVIEW_SUBMISSION_ERROR'; 




