
export const PRODUCT_GET_REQUEST = 'PRODUCT_GET_REQUEST';
export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
export const PRODUCT_GET_ERROR = 'PRODUCT_GET_ERROR'; 

export const PRODUCT_DETAILS_GET_REQUEST = 'PRODUCT_DETAILS_GET_REQUEST';
export const PRODUCT_DETAILS_GET_SUCCESS = 'PRODUCT_DETAILS_GET_SUCCESS';
export const PRODUCT_DETAILS_GET_ERROR = 'PRODUCT_DETAILS_GET_ERROR';